spring:
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:15432/securenotes}
    username: ${SPRING_DATASOURCE_USERNAME:securenotes}
    password: ${SPRING_DATASOURCE_PASSWORD:securenotes_dev_password}
    driver-class-name: org.postgresql.Driver

  flyway:
    enabled: true
    locations: classpath:db/migration

  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        format_sql: true

logging:
  level:
    root: INFO
    com.securenotes: DEBUG
    org.springframework.web: DEBUG
    org.springframework.security: DEBUG
    org.springframework.data: DEBUG
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql: TRACE

jwt:
  private-key: ${JWT_PRIVATE_KEY:-----BEGIN PRIVATE KEY-----\nMIIEvQIBADANBgkqhkiG9w0BAQEFAASCBKcwggSjAgEAAoIBAQDJ3RWAYWdIC2rHg49q+EhJPOgI1e/nd6l+wYL9b90JWVndxCFj/6X42R//PeNgGO01jZuPwQg+cNsrmVo31z9ojujMq7i5wrTTFdO5q4isyrh83H9787L1zg0xBqf0qi3QRv0DBETdW5rHNYqjj8aipdwpQF4GDndQl1M1mUByQpTJ7pOIoUyXLnxbn/rn2ENOItn6vpTLAgd78oPYMSy9SKdk12108Msxa8pU/ATzY4fZhIALwSnjs0o9PKfzrtQfzNycb0J1B2zHyvUF1tkSWzuMrM4M1CXJdrCSKGSoHU4SXWELGeLa+wnNgNPCcXp+yIbtoRKBNg0Fha8bMxllAgMBAAECggEAIXif59Nex36jJDVfirZj8AbiF5L3rkr0ZxDpqiHKBhKTeNbcTYM2j0JbUJx/ru+7J2HVXTr95bKbWMmbAL7XY/wsREGmBeEvz/9ixbrYVQRhHk0Gc3RXZHQX0lz+7O3p3krjCYTD8WtOyQDK/e9pWY9EZ++lF35/ELUixjSkz70IlIE0LVwTDn2wH5i9Ws/eSaL9TCdkjBM6lkIIdCk6j+UKjygrOv8QhtndFakCvFCJ03TtuAb5Y7T0oFsoFWYCWjmYsCrHLujyErSOhOw2nNPqA5FPDBRiUS22tyT7+iK08HHaSJpy7bph3tfKBXid0122IlithGD0ip1sznmnqQKBgQDrsarR3fZuUi1yi/safVy2R3RJ3tJh8yiRVO15gAk44j2ADNxZ1QI6yshY5pKkKlavaq+fcfoqrBW5NvBkIq2Pao0VXvLlhu71r2fSWy72MbaeGXLAgeoAEZjGD8rAraE7pGWN5HLMhqiCx0t8rliNgu3hBh57ojzlM69MFwdGfQKBgQDbQUXLv3+opNUonk+LYDlEj67yggTb9KwUNDujIDgMnL9kVLfuzi/p5/IQWotE03TW4NK9v12ZltdLLeR1Ik7DQzMeK1RFSPrM0dPilUt/FZzfwTtYjGH746wj6XIIeXhjp4H7V5bTU3MEg1DXb0CPpaLu4s8OZ0l3jOhAZmdLCQKBgQDY1MaV9GG19Jwi+Wy1XgdhGjN9kiRyQEVeDoe6c3QIhPqXRz2g1zoJ5GyUfOsDZIADOV8AjNbdUxtZHZXiSZTqj9fjhUpops5H8GrPN1vo2qtqn3bWa65fCdFGxVh+Ej52pDNZaoXCa0+zoK1tsud8qKs3jW2VyBfFtNrcYYMr8QKBgHXGhjuATo7EnEwJXik8MwcFN7DE7t9IevcPZ8mkkPcVbCn06Ci7UTmQgpMOUClUfTq/4fRTS3ApetTDfij9mNmCy361P7tIDJDhVbQtBjTp4y6+maZjIm8wSVOxHrQ2q9i8LjJZRoeWF/6gm1heRovjKbaw1xChovE5G7kcSPghAoGAB2Gt/ORdl/gDXp3ek7yGRmRVB5Hd28gy2LmWKfnmBS8V+HsmgG8GbB8fYtmbRnv6P1AdDkrEU4J6R3QRjm54miROEv7l1Wlp0x+4EmAkKsmgNE1aG0sLJ5Jjw1oFzDh49EAyitZnahbTBxnul3CxFUknKzvCc7B9/aKTsrdgqPM=\n-----END PRIVATE KEY-----}
  public-key: ${JWT_PUBLIC_KEY:-----BEGIN PUBLIC KEY-----\nMIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAyd0VgGFnSAtqx4OPavhISTzoCNXv53epfsGC/W/dCVlZ3cQhY/+l+Nkf/z3jYBjtNY2bj8EIPnDbK5laN9c/aI7ozKu4ucK00xXTuauIrMq4fNx/e/Oy9c4NMQan9Kot0Eb9AwRE3VuaxzWKo4/GoqXcKUBeBg53UJdTNZlAckKUye6TiKFMly58W5/659hDTiLZ+r6UywIHe/KD2DEsvUinZNdtdPDLMWvKVPwE82OH2YSAC8Ep47NKPTyn867UH8zcnG9CdQdsx8r1BdbZEls7jKzODNQlyXawkihkqB1OEl1hCxni2vsJzYDTwnF6fsiG7aESgTYNBYWvGzMZZQIDAQAB\n-----END PUBLIC KEY-----}
  expiration: 86400

server:
  port: 8080
